"use strict";

const { createMcpRuntimeHandlers } = require("./mcp_runtime_handlers");
const { runServerLifecycle } = require("./server_lifecycle");

function runConfiguredRuntime({
  bootstrapConfig,
  host,
  port,
  dispatchCreateServerRoute,
  handleHealthRoute,
  handleDocsRoute,
  handleNotFoundRoute,
  jsonResponse,
  textResponse,
  fetchDoc,
  documentRuntimeContext,
  serverName,
  serverVersion,
  connectorShapeVersion,
  outputMode,
  maxFetchTextChars,
  auditVersion,
  authPolicy,
  runtimeProfile,
  stageStatus,
  securityBoundary,
  publicBaseUrl,
  toolsList,
  authorizationServerMetadataProvider,
  oauth21AuthorizationServer,
  optionalTools,
  getOptionalTool,
  auditLog,
  startupReportVersion,
  labelsVersion,
  auditLogPath,
  rateLimiter,
}) {
  const { handleMcp } = createMcpRuntimeHandlers({
    serverName,
    serverVersion,
    connectorShapeVersion,
    outputMode,
    authPolicy,
    runtimeProfile,
    toolsList,
    documentRuntimeContext,
    auditLog,
    getOptionalTool,
    publicBaseUrl,
    rateLimiter,
  });

  return runServerLifecycle({
    selfTest: bootstrapConfig.selfTest,
    selfTestContext: {
      toolsList,
      optionalTools,
      getOptionalTool,
      authPolicy,
      runtimeProfile,
      outputMode,
      maxFetchTextChars,
      connectorShapeVersion,
      documentRuntimeContext,
      auditLogPath,
    },
    startupContext: {
      host,
      port,
      dispatchCreateServerRoute,
      handleMcp,
      handleHealthRoute,
      handleDocsRoute,
      handleNotFoundRoute,
      jsonResponse,
      textResponse,
      fetchDoc,
      documentRuntimeContext,
      serverName,
      serverVersion,
      connectorShapeVersion,
      outputMode,
      maxFetchTextChars,
      auditVersion,
      authPolicy,
      runtimeProfile,
      stageStatus,
      securityBoundary,
      publicBaseUrl,
      toolsList,
      authorizationServerMetadataProvider,
      oauth21AuthorizationServer,
      auditLog,
      bootstrapAuthMode: bootstrapConfig.authMode,
      startupReportVersion,
      labelsVersion,
      auditLogPath,
    },
  });
}

module.exports = {
  runConfiguredRuntime,
};
