#!/usr/bin/env node
'use strict';
const fs=require('fs');
const { loadCombinedServerSpec } = require('./load_server_specs');
const spec=JSON.parse(fs.readFileSync(process.argv[2]||'SERVER_SPEC.json','utf8'));
const state=JSON.parse(fs.readFileSync(process.argv[3]||'_workflow/state.json','utf8'));
const errors=[];
const e=(m)=>errors.push(m);
const b=(o,k,v,n)=>{if(!o||o[k]!==v)e(n+'.'+k+' must be '+v)};
const q=(o,k,v,n)=>{if(!o||o[k]!==v)e(n+'.'+k+' must be '+JSON.stringify(v))};
const plan=spec.decision_runtime_integration_plan||{};
q(plan,'status','plan_written_not_implemented','plan');
b(plan,'runtime_behavior_changed',false,'plan');
b(plan,'server_runtime_integrated',false,'plan');
b(plan,'operator_approval_required_before_runtime_patch',true,'plan');
const gate=spec.decision_runtime_operator_gate||{};
q(gate,'status','operator_gate_written_runtime_patch_not_authorized','gate');
q(gate,'mode','operator_approval_gate_only_no_runtime_change','gate');
b(gate,'eligible_for_operator_runtime_patch_review',true,'gate');
b(gate,'operator_approval_required_for_runtime_patch',true,'gate');
b(gate,'runtime_patch_authorized',false,'gate');
b(gate,'server_runtime_integrated',false,'gate');
b(gate,'mcp_tool_exposed',false,'gate');
b(gate,'connector_visible_change_allowed',false,'gate');
const d=gate.gate_decision||{};
b(d,'plan_validated',true,'decision');
b(d,'ready_to_request_operator_runtime_patch_approval',true,'decision');
b(d,'runtime_patch_allowed_next',false,'decision');
q(d,'next_planned_step','stage12_step29_decision_runtime_patch_scope_approval_package','decision');
const files=Array.isArray(gate.runtime_patch_candidate_files)?gate.runtime_patch_candidate_files:[];
if(files.length<7)e('candidate file count must be >=7');
if(!files.every(x=>x.approved_for_patch_now===false))e('all candidate files must remain unapproved');
const cur=state.current_work_package||{};
q(cur,'id','stage12_step28_decision_runtime_operator_gate','state.current');
b(cur,'runtime_code_changed',false,'state.current');
b(cur,'restart_pending',false,'state.current');
const a=cur.acceptance||{};
b(a,'operator_gate_written',true,'acceptance');
b(a,'ready_to_request_operator_runtime_patch_approval',true,'acceptance');
b(a,'runtime_patch_authorized',false,'acceptance');
b(a,'runtime_patch_allowed_next',false,'acceptance');
q(a,'next_planned_step','stage12_step29_decision_runtime_patch_scope_approval_package','acceptance');
if(state.last_validation?.decision_runtime_operator_gate!=='ok')e('last_validation.decision_runtime_operator_gate must be ok');
if(!Array.isArray(state.validation_evidence)||!state.validation_evidence.some(x=>x.id==='stage12_step28_decision_runtime_operator_gate_pass'))e('missing Step 28 evidence');
const out={ok:errors.length===0,gate_status:gate.status,runtime_patch_authorized:gate.runtime_patch_authorized===true,runtime_patch_allowed_next:d.runtime_patch_allowed_next===true,candidate_file_count:files.length,errors};
console.log(JSON.stringify(out,null,2));
if(!out.ok)process.exit(1);
