"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
function read(p){ return JSON.parse(fs.readFileSync(p,"utf8")); }
const root = read("SERVER_SPEC.json");
const auth = read("SERVER_AUTH_SPEC.json");
const profiles = read("SERVER_PROFILES_SPEC.json");
const tools = read("SERVER_TOOLS_SPEC.json");
const spec = read("SERVER_AUTHZ_DECISION_SPEC.json");
const ref = "SERVER_AUTHZ_DECISION_SPEC.json";
const runtimeRef = "SERVER_POLICY_RUNTIME_SPEC.json";
const runtime = read(runtimeRef);
assert.equal(spec.schema_version, "mcp-tests-server-authz-decision-spec-v1");
assert.equal(spec.spec_mode, "canonical_structured_spec_not_progress_log");
assert.deepEqual(spec.applies_to, ["SERVER_AUTH_SPEC.json", "SERVER_PROFILES_SPEC.json", "SERVER_TOOLS_SPEC.json", "SERVER_RESOURCE_POLICY_SPEC.json", "SERVER_MEMORY_POLICY_SPEC.json", "SERVER_NETWORK_POLICY_SPEC.json", "SERVER_DATABASE_POLICY_SPEC.json", "SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json"]);
assert.equal(spec.cross_category_rules.no_cli_extension, true);
assert.equal(spec.source_salvage.runtime_enforced, true);
assert.equal(spec.decision_runtime_spec_ref, "SERVER_DECISION_RUNTIME_SPEC.json");
assert.equal(runtime.runtime_enforced, true);
assert.equal(spec.source_salvage.connector_visible, false);
assert.equal(spec.decision_model.default_decision, "deny");
assert.ok(spec.decision_model.input_sections.includes("auth_context"));
assert.ok(spec.decision_model.input_sections.includes("profile_context"));
assert.ok(spec.decision_model.input_sections.includes("tool_context"));
assert.ok(spec.decision_model.output_fields.includes("audit_receipt"));
assert.ok(spec.reason_codes.includes("DENY_DEFAULT"));
assert.ok(spec.reason_codes.includes("DENY_UNKNOWN_TOOL"));
assert.ok(spec.interface_contract.fail_closed_semantics.deny_on_unknown_tool);
assert.ok(spec.interface_contract.fail_closed_semantics.deny_on_runtime_surface_drift);
assert.equal(spec.interface_contract.audit_receipt_contract.secret_material_allowed, false);
assert.equal(root.spec_refs.policy_decision, ref);
assert.equal(auth.decision_spec_ref, ref);
assert.equal(profiles.server_profiles.decision_spec_ref, ref);
assert.equal(tools.policy_decision_ref, ref);
assert.equal(runtime.schema_version, "mcp-tests-server-policy-runtime-spec-v1");
assert.equal(root.spec_refs.policy_runtime, runtimeRef);
assert.equal(spec.policy_runtime_ref, runtimeRef);
assert.equal(profiles.server_profiles.policy_runtime_ref, runtimeRef);
assert.equal(tools.policy_runtime_ref, runtimeRef);
assert.equal(root.spec_refs.resource_policy, "SERVER_RESOURCE_POLICY_SPEC.json");
assert.equal(spec.resource_policy_ref, "SERVER_RESOURCE_POLICY_SPEC.json");
assert.equal(root.spec_refs.memory_policy, "SERVER_MEMORY_POLICY_SPEC.json");
assert.equal(spec.memory_policy_ref, "SERVER_MEMORY_POLICY_SPEC.json");
assert.equal(root.spec_refs.network_policy, "SERVER_NETWORK_POLICY_SPEC.json");
assert.equal(spec.network_policy_ref, "SERVER_NETWORK_POLICY_SPEC.json");
assert.equal(root.spec_refs.database_policy, "SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(spec.database_policy_ref, "SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(root.spec_refs.plugin_visibility_policy, "SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(spec.plugin_visibility_policy_ref, "SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(Boolean(root.cli?.parameters?.["--decision"]), false);
assert.equal(Boolean(root.cli?.parameters?.["--authz"]), false);
assert.equal(Boolean(root.cli?.parameters?.["--policy-decision"]), false);
assert.equal(Boolean(root.cli?.parameters?.["--policy-runtime"]), false);
console.log("smoke_cross_category_spec ok");
