"use strict";
const assert=require("node:assert/strict");
const spec=require("../SERVER_CONNECTOR_SURFACE_SPEC.json");
const tools=require("../SERVER_TOOLS_SPEC.json");
const pol=require("../src/tool_policy");
assert.equal(spec.schema_version,"mcp-tests-connector-surface-spec-v1");
assert.equal(spec.spec_mode,"refresh-readiness-contract-not-live-connector-state");
assert.equal(spec.public_connector.profile,"public");
assert.equal(spec.public_connector.auth_mode,"none");
assert.deepEqual([...spec.public_connector.expected_tools].sort(),[...pol.PUBLIC_TOOL_NAMES].sort());
assert.deepEqual([...spec.public_connector.expected_tools].sort(),[...tools.surface_classes.public_mcp_tools.tools].sort());
assert.equal(spec.public_connector.expected_tool_count,pol.PUBLIC_TOOL_NAMES.length);
for(const n of spec.public_connector.forbidden_tool_names) assert.equal(spec.public_connector.expected_tools.includes(n),false,`${n} forbidden public`);
assert.equal(spec.public_connector.refresh_required_before_live_use,true);
assert.equal(spec.operator_connector.separate_from_public_connector,true);
assert.equal(spec.operator_connector.must_not_be_labeled_public,true);
assert.equal(spec.authenticated_connector.oauth_before_production_required,true);
for(const n of pol.AUTHORIZED_MCP_TOOL_NAMES) assert.ok(spec.authenticated_connector.expected_authorized_tools.includes(n),`${n} auth connector`);
console.log("smoke_connector_refresh_readiness_spec ok");
