"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const root=read("SERVER_SPEC.json"),spec=read("SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json"),res=read("SERVER_RESOURCE_POLICY_SPEC.json"),db=read("SERVER_DATABASE_POLICY_SPEC.json"),authz=read("SERVER_AUTHZ_DECISION_SPEC.json"),profiles=read("SERVER_PROFILES_SPEC.json"),tools=read("SERVER_TOOLS_SPEC.json"),pub=read("profiles/public.json"),tests=read("profiles/tests.json");
const {validateProfileObject}=require("../src/profile_schema_validator");
assert.equal(spec.schema_version,"mcp-tests-server-plugin-visibility-policy-spec-v1");
assert.equal(spec.runtime_enforced,false);assert.equal(spec.connector_visible,false);
assert.deepEqual(spec.registry_states,["candidate","enabled","disabled","quarantined"]);
assert.equal(spec.derived_states.visible.not_directly_stored_as_registry_state,true);
assert.equal(spec.derived_states.callable.not_directly_stored_as_registry_state,true);
assert.equal(spec.state_separation_rules.visibility_is_not_callability,true);
assert.equal(spec.apply_rules.operator_approval_required_for_apply,true);
assert.equal(spec.safety_rules.no_cli_extension,true);
assert.equal(root.spec_refs.plugin_visibility_policy,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(authz.plugin_visibility_policy_ref,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(res.plugin_visibility_policy_ref,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(db.plugin_visibility_policy_ref,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(profiles.server_profiles.plugin_visibility_policy_ref,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(tools.plugin_visibility_policy_ref,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
const expected={plugin_registry_status:"plugin_registry_read",plugin_registry_audit:"plugin_registry_read",plugin_visibility_plan:"plugin_visibility_plan",plugin_visibility_status:"plugin_visibility_status",plugin_execution_preflight:"plugin_execution_preflight",plugin_execute_readonly:"plugin_execution_readonly"};
for(const [name,scope] of Object.entries(expected)){assert.equal(spec.tool_bindings[name].scope,scope,name);assert.equal(tools.tool_catalog[name].plugin_visibility_policy_ref,"SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json",name)}
for(const surf of Object.values(pub.surfaces))assert.deepEqual(surf.allowed_plugin_scopes,[]);
assert.deepEqual(tests.surfaces.public.allowed_plugin_scopes,[]);
assert.deepEqual(tests.surfaces.authenticated.allowed_plugin_scopes,["plugin_registry_read","plugin_visibility_plan","plugin_visibility_status","plugin_execution_preflight","plugin_execution_readonly"]);
let bad=JSON.parse(JSON.stringify(pub));bad.surfaces.public.allowed_plugin_scopes=["plugin_registry_read"];
let r=validateProfileObject(bad,{expectedName:"public",profilePath:"profiles/public.json"});assert.equal(r.ok,false);assert.ok(r.errors.join(";").includes("must be empty on public surface"));
bad=JSON.parse(JSON.stringify(tests));bad.surfaces.authenticated.allowed_plugin_scopes=["unknown_plugin_scope"];
r=validateProfileObject(bad,{expectedName:"tests",profilePath:"profiles/tests.json"});assert.equal(r.ok,false);assert.ok(r.errors.join(";").includes("unknown plugin scope"));
assert.equal(Boolean(root.cli?.parameters?.["--plugin-visibility-policy"]),false);
console.log("smoke_plugin_visibility_policy_spec ok");
