"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const read = (p) => JSON.parse(fs.readFileSync(p, "utf8"));
const ref = "SERVER_POLICY_RUNTIME_SPEC.json";
const root = read("SERVER_SPEC.json");
const runtime = read(ref);
const authz = read("SERVER_AUTHZ_DECISION_SPEC.json");
const resource = read("SERVER_RESOURCE_POLICY_SPEC.json");
const profiles = read("SERVER_PROFILES_SPEC.json");
const tools = read("SERVER_TOOLS_SPEC.json");
const memory = read("SERVER_MEMORY_POLICY_SPEC.json");
const network = read("SERVER_NETWORK_POLICY_SPEC.json");
const database = read("SERVER_DATABASE_POLICY_SPEC.json");
const plugin = read("SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json");
assert.equal(runtime.schema_version, "mcp-tests-server-policy-runtime-spec-v1");
assert.equal(runtime.spec_mode, "canonical_structured_spec_not_progress_log");
assert.equal(runtime.runtime_enforced, true);
assert.equal(runtime.connector_visible, false);
assert.equal(runtime.no_cli_extension, true);
assert.deepEqual(runtime.applies_to, ["SERVER_AUTH_SPEC.json", "SERVER_PROFILES_SPEC.json", "SERVER_TOOLS_SPEC.json", "SERVER_AUTHZ_DECISION_SPEC.json", "SERVER_RESOURCE_POLICY_SPEC.json", "SERVER_MEMORY_POLICY_SPEC.json", "SERVER_NETWORK_POLICY_SPEC.json", "SERVER_DATABASE_POLICY_SPEC.json", "SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json"]);
assert.deepEqual(runtime.composition_pipeline, ["normalize_request_context", "derive_auth_context", "load_profile_surface", "load_tool_catalog_entry", "resolve_resource_policy", "resolve_specific_policy_refs", "evaluate_authz_decision", "build_audit_receipt", "allow_or_deny"]);
assert.equal(root.spec_refs.policy_runtime, ref);
assert.equal(authz.policy_runtime_ref, ref);
assert.equal(resource.policy_runtime_ref, ref);
assert.equal(profiles.server_profiles.policy_runtime_ref, ref);
assert.equal(tools.policy_runtime_ref, ref);
assert.equal(memory.policy_runtime_ref, ref);
assert.equal(network.policy_runtime_ref, ref);
assert.equal(database.policy_runtime_ref, ref);
assert.equal(plugin.policy_runtime_ref, ref);
for (const field of ["allowed", "decision", "reason_codes", "tool_name", "profile", "auth_mode", "surface_class", "resource_class", "operation_class", "policy_refs", "audit_receipt"]) assert.ok(runtime.output_contract.required_fields.includes(field), field);
for (const rule of ["unknown_tool_denied", "missing_tool_catalog_entry_denied", "missing_resource_policy_denied", "unknown_resource_class_denied", "unknown_operation_class_denied", "missing_specific_policy_when_required_denied", "profile_surface_mismatch_denied", "auth_profile_surface_mismatch_denied", "public_surface_non_public_policy_denied", "runtime_surface_drift_denied", "audit_receipt_build_failure_denied"]) assert.equal(runtime.fail_closed_rules[rule], true, rule);
const catalog = tools.tool_catalog;
const names = Object.values(tools.surface_classes).flatMap((surface) => surface.tools || []);
assert.equal(Object.keys(catalog).length, names.length);
for (const name of names) {
  const item = catalog[name];
  assert.ok(item, name + " catalog entry");
  assert.equal(item.name, name);
  assert.ok(resource.resource_classes[item.resource_class], name + " resource_class");
  assert.ok(resource.operation_classes[item.operation_class], name + " operation_class");
  assert.ok(item.resource_policy_refs.includes("SERVER_RESOURCE_POLICY_SPEC.json"), name + " resource policy ref");
  if (name.startsWith("memory_")) assert.equal(item.memory_policy_ref, "SERVER_MEMORY_POLICY_SPEC.json", name);
  if (name.startsWith("net_")) assert.equal(item.network_policy_ref, "SERVER_NETWORK_POLICY_SPEC.json", name);
  if (name.startsWith("plugin_")) assert.equal(item.plugin_visibility_policy_ref, "SERVER_PLUGIN_VISIBILITY_POLICY_SPEC.json", name);
}
assert.equal(database.current_database_runtime.direct_mcp_database_tools_present, false);
assert.equal(database.current_database_runtime.raw_sql_tools_present, false);
assert.equal(names.some((name) => name.startsWith("db_") || name.includes("sql")), false);
assert.equal(Boolean(root.cli?.parameters?.["--policy-runtime"]), false);
assert.equal(Boolean(root.cli?.parameters?.["--runtime-policy"]), false);
assert.equal(Boolean(root.cli?.parameters?.["--policy-runtime-enforce"]), false);
console.log("smoke_policy_runtime_spec ok");
