"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8");
const readJson = (rel) => JSON.parse(read(rel));
const record = read("_workflow/operator_decisions/s8_isolated_sessionless_activation_regression.md");
assert.ok(record.includes("Status: GREEN / ISOLATED HIGHER-PORT ACTIVATION PASSED / CONNECTOR UNCHANGED"));
assert.ok(record.includes("port: 3020"));
assert.ok(record.includes("tools_count: 43"));
assert.ok(record.includes("protocol version: `2025-06-18`"));
assert.ok(record.includes("missing_header"));
assert.ok(record.includes("version_mismatch"));
assert.ok(record.includes("bad_version"));
assert.ok(record.includes("JSON-RPC `-32004`"));
assert.ok(record.includes("audit had 15 lines"));
assert.ok(record.includes("raw handle was not present"));
assert.ok(record.includes("port 3020 closed"));
assert.ok(record.includes("no OAuth21 3008 restart"));
assert.ok(record.includes("no connector refresh"));
assert.ok(record.includes("no connector route migration"));
const state = readJson("_workflow/state.json");
assert.ok(["passed_higher_port", "passed"].includes(state.sessionless_target_selection.s8_isolated_activation.status));
assert.equal(state.sessionless_target_selection.s8_isolated_activation.port, 3020);
const inventory = readJson("_workflow/sessionless_inventory.json");
assert.equal(inventory.target_selection_readiness.s8_isolated_activation.status, "passed_higher_port_no_connector_change");
assert.equal(inventory.target_selection_readiness.s8_isolated_activation.port, 3020);
assert.equal(inventory.target_selection_readiness.s8_isolated_activation.audit_raw_handle_seen, false);
assert.equal(inventory.target_selection_readiness.s8_isolated_activation.cleanup.port_open_after, false);
const runAll = readJson("_tests/run_all_smoke_scripts.json");
assert.ok(runAll.includes("_tests/smoke_s8_isolated_sessionless_activation_regression.js"));
console.log("smoke_s8_isolated_sessionless_activation_regression ok");
