"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
function read(p){ return JSON.parse(fs.readFileSync(p,"utf8")); }
const root = read("SERVER_SPEC.json");
const auth = read("SERVER_AUTH_SPEC.json");
const profiles = read("SERVER_PROFILES_SPEC.json");
const tools = read("SERVER_TOOLS_SPEC.json");
const spec = read("SERVER_AUTHZ_DECISION_SPEC.json");
assert.equal(spec.schema_version, "mcp-tests-server-authz-decision-spec-v1");
assert.equal(spec.spec_mode, "canonical_structured_spec_not_progress_log");
assert.deepEqual(spec.applies_to, ["auth", "profiles", "tools"]);
assert.equal(spec.cli_contract.new_cli_parameters_allowed, false);
assert.equal(spec.decision_model.runtime_enforced, false);
assert.equal(spec.decision_model.mcp_tool_exposed, false);
assert.equal(spec.decision_model.default_decision, "deny");
assert.ok(spec.decision_model.input_sections.includes("auth_context"));
assert.ok(spec.decision_model.input_sections.includes("profile_context"));
assert.ok(spec.decision_model.input_sections.includes("tool_context"));
assert.ok(spec.decision_model.output_fields.includes("audit_receipt"));
assert.ok(spec.decision_model.reason_codes.includes("DENY_DEFAULT"));
assert.ok(spec.decision_model.reason_codes.includes("DENY_UNKNOWN_TOOL"));
assert.ok(spec.fail_closed_semantics.deny_on_unknown_tool);
assert.ok(spec.fail_closed_semantics.deny_on_runtime_surface_drift);
assert.equal(spec.audit_receipt_contract.secret_material_allowed, false);
assert.equal(spec.implementation_boundary.connector_visible_change_allowed, false);
assert.equal(root.spec_refs.authz_decision || root.spec_refs.cross_category_policy || root.spec_refs.decision, "SERVER_AUTHZ_DECISION_SPEC.json");
assert.equal(root.authz_decision.spec_ref, "SERVER_AUTHZ_DECISION_SPEC.json");
assert.equal(auth.decision_spec_ref, "SERVER_AUTHZ_DECISION_SPEC.json");
assert.equal(profiles.server_profiles.decision_ref, "SERVER_AUTHZ_DECISION_SPEC.json");
assert.equal(tools.policy_decision_ref, "SERVER_AUTHZ_DECISION_SPEC.json");
console.log("smoke_stage12_policy_spec ok");
