"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const m = require("../src/sessionless_target_selection_readiness");
const ROOT = path.resolve(__dirname, "..");
function read(rel) { return fs.readFileSync(path.join(ROOT, rel), "utf8"); }
const r = m.buildSessionlessTargetSelectionReadiness();
assert.equal(r.success, true);
assert.equal(r.readiness_version, m.SESSIONLESS_TARGET_SELECTION_READINESS_VERSION);
assert.equal(r.source_verification.verified_at, "2026-06-29");
assert.equal(r.current_dependencies.initialize_handshake.present, true);
assert.equal(r.current_dependencies.mcp_session_id_header.present, true);
assert.equal(r.current_dependencies.session_store.present, true);
assert.equal(r.current_dependencies.get_sse_stream.present, true);
assert.equal(r.current_dependencies.pending_request_correlation.present, true);
assert.equal(r.current_dependencies.sampling_roundtrip.present, true);
assert.equal(r.current_dependencies.cooperative_cancellation.present, true);
assert.equal(r.current_dependencies.hotplug_readiness.present, true);
assert.equal(r.options.keep_stable_connector_current.status, "recommended_for_live_oauth21_connector");
assert.equal(r.options.parallel_draft_sessionless_prototype.status, "recommended_next_implementation_target_after_operator_selection");
assert.equal(r.options.full_switch_now.status, "not_recommended");
assert.equal(r.decision.target_selection_status, "prepared_pending_operator_selection");
assert.equal(r.decision.do_not_remove_current_session_code, true);
assert.equal(r.decision.do_not_change_live_connector_route, true);
assert.equal(r.explicit_state_handle_rules.handles_are_tool_design_pattern_not_protocol_feature, true);
assert.equal(r.explicit_state_handle_rules.handles_are_ordinary_tool_arguments_and_structured_content_fields, true);
assert.equal(r.explicit_state_handle_rules.opaque_ids_required, true);
assert.equal(r.explicit_state_handle_rules.possession_is_not_authorization, true);
assert.equal(r.explicit_state_handle_rules.auth_context_must_be_checked_on_every_handle_use, true);
assert.ok(r.blocker_reassessment.stale_blockers_removed.includes("C3 cooperative cancellation not implemented"));
assert.ok(r.blocker_reassessment.stale_blockers_removed.includes("event-driven hotplug lifecycle not mapped"));
assert.ok(r.blocker_reassessment.valid_blockers_remaining.includes("final operator target selection is still required before prototype"));
assert.equal(r.current_behavior_change, false);
assert.equal(r.runtime_restart_required_now, false);
assert.equal(r.connector_refresh_required_now, false);
assert.equal(r.schema_change_required_now, false);
assert.equal(r.public_3009_start_required_now, false);
const inventory = JSON.parse(read("_workflow/sessionless_inventory.json"));
assert.equal(inventory.target_selection_readiness.status, "prepared_pending_operator_selection");
assert.equal(inventory.target_selection_readiness.recommended_target, "parallel_draft_sessionless_prototype_while_keeping_stable_connector_current");
assert.equal(inventory.target_selection_readiness.connector_refresh_required_now, false);
assert.equal(inventory.target_selection_readiness.runtime_restart_required_now, false);
assert.equal(inventory.target_selection_readiness.do_not_remove_current_session_code, true);
console.log("smoke_sessionless_target_selection_readiness ok");
