"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const crypto=require("node:crypto");
const os=require("node:os");
const path=require("node:path");
const spec=require("../SERVER_AUTH_SPEC.json");
const {createAuthPolicy,authResponseHeaders}=require("../src/auth/auth_policy");
const {buildProtectedResourceMetadata}=require("../src/runtime/oauth_metadata");
function b64(o){return Buffer.from(JSON.stringify(o)).toString("base64url");}
function sign(payload,secret){const h=b64({alg:"HS256",typ:"JWT"});const p=b64(payload);const s=crypto.createHmac("sha256",secret).update(h+"."+p).digest("base64url");return h+"."+p+"."+s;}
assert.equal(spec.schema_version,"mcp-tests-auth-spec-v1");
assert.equal(spec.resource_server.protected_resource_metadata_required,true);
assert.equal(spec.resource_server.query_token_forbidden,true);
assert.equal(spec.resource_server.audience_binding_required,true);
assert.equal(spec.scope_matrix["mcp:tools"].profile,"internal");
const meta=buildProtectedResourceMetadata({publicBaseUrl:"https://mcp.example/mcp"});
assert.equal(meta.resource,"https://mcp.example/mcp");
assert.ok(meta.authorization_servers.length>=1);
assert.ok(meta.scopes_supported.includes("mcp:tools"));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mcp-oauth-"));const secretFile=path.join(dir,"secret.txt");const secret="s".repeat(48);fs.writeFileSync(secretFile,secret);
const policy=createAuthPolicy({mode:"oauth",publicBaseUrl:"https://mcp.example/mcp",oauthIssuer:"https://as.example",oauthAudience:"https://mcp.example/mcp",oauthHmacSecretFile:secretFile});
const now=Math.floor(Date.now()/1000);
const good=sign({iss:"https://as.example",aud:"https://mcp.example/mcp",sub:"u",scope:"mcp:tools",exp:now+60},secret);
assert.equal(policy.authenticate({headers:{authorization:"Bearer "+good},url:"/mcp"}).ok,true);
assert.equal(policy.authenticate({headers:{authorization:"Bearer "+good},url:"/mcp?token=x"}).error,"query_token_forbidden");
const badAud=sign({iss:"https://as.example",aud:"https://other.example",scope:"mcp:tools",exp:now+60},secret);
assert.equal(policy.authenticate({headers:{authorization:"Bearer "+badAud},url:"/mcp"}).error,"invalid_audience");
const noScope=sign({iss:"https://as.example",aud:"https://mcp.example/mcp",scope:"other",exp:now+60},secret);
assert.equal(policy.authenticate({headers:{authorization:"Bearer "+noScope},url:"/mcp"}).status,403);
assert.ok(authResponseHeaders(policy)["www-authenticate"].includes("oauth-protected-resource"));
fs.rmSync(dir,{recursive:true,force:true});
console.log("smoke_stage12_oauth_preflight_contract ok");
