"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const spec = require("../SERVER_AUTH_SPEC.json");
const policy = spec.client_id_metadata_document_policy;
assert.equal(policy.status, "implemented_p3");
assert.equal(policy.ietf_reference, "draft-ietf-oauth-client-id-metadata-document-02");
assert.equal(policy.mcp_spec_version, "2026-07-28");
assert.equal(policy.authorization_server_metadata_flag, "client_id_metadata_document_supported=true");
assert.equal(policy.client_id_scheme_required, "https");
assert.equal(policy.client_id_path_required, true);
assert.equal(policy.userinfo_forbidden, true);
assert.equal(policy.fragment_forbidden, true);
assert.equal(policy.dot_segments_forbidden, true);
assert.equal(policy.http_redirects_followed, false);
assert.equal(policy.successful_http_status_required, 200);
assert.equal(policy.maximum_bytes_read_and_processed, 5120);
assert.match(policy.dns_policy, /RFC6890/);
assert.match(policy.transport_policy, /prevalidated_DNS_addresses/);
assert.equal(policy.metadata_client_id_exact_string_match_required, true);
assert.equal(policy.redirect_uri_exact_string_match_required, true);
for (const field of ["client_id", "client_name", "redirect_uris"]) assert.ok(policy.metadata_required_fields.includes(field));
assert.deepEqual(policy.allowed_token_endpoint_auth_methods, ["none"]);
assert.equal(policy.private_key_jwt_supported, false);
assert.equal(policy.shared_secret_metadata_forbidden, true);
assert.equal(policy.private_key_material_forbidden, true);
assert.equal(policy.secondary_metadata_urls_fetched, false);
assert.equal(policy.invalid_or_error_documents_cached, false);
assert.equal(policy.http_cache_headers_respected_with_bounded_lifetime, true);
assert.equal(policy.http_cache_age_accounted_for, true);
assert.equal(policy.persistent_client_registry_write, false);
assert.equal(policy.dcr_fallback_retained, true);
for (const guard of ["_tests/smoke_oauth_cimd_resolver.js", "_tests/smoke_oauth21_cimd_flow.js"]) assert.ok(policy.guards.includes(guard));
const resolverSource = fs.readFileSync(path.join(__dirname, "..", "src", "auth", "oauth_cimd_resolver.js"), "utf8");
assert.match(resolverSource, /lookup:\s*pinnedLookup\(resolvedAddresses\)/, "default HTTPS transport must stay DNS-pinned to prevalidated addresses");
assert.match(resolverSource, /request\.destroy\(cimdError\("cimd_response_too_large"\)\)/, "streaming read limit must abort before processing an oversized document");
console.log("smoke_oauth_cimd_policy ok");
