"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
function read(p){return JSON.parse(fs.readFileSync(p,"utf8"));}
const root=read("SERVER_SPEC.json");
const mem=read("SERVER_MEMORY_POLICY_SPEC.json");
const res=read("SERVER_RESOURCE_POLICY_SPEC.json");
const authz=read("SERVER_AUTHZ_DECISION_SPEC.json");
const profiles=read("SERVER_PROFILES_SPEC.json");
const tools=read("SERVER_TOOLS_SPEC.json");
const pub=read("profiles/public.json");
const tests=read("profiles/tests.json");
const { validateProfileObject } = require("../src/profile_schema_validator");
assert.equal(mem.schema_version,"mcp-tests-server-memory-policy-spec-v1");
assert.equal(mem.runtime_enforced,false);
assert.equal(mem.safety_rules.no_cli_extension,true);
assert.equal(mem.safety_rules.public_surface_memory_forbidden,true);
assert.equal(root.spec_refs.memory_policy,"SERVER_MEMORY_POLICY_SPEC.json");
assert.equal(authz.memory_policy_ref,"SERVER_MEMORY_POLICY_SPEC.json");
assert.equal(res.memory_policy_ref,"SERVER_MEMORY_POLICY_SPEC.json");
assert.equal(profiles.server_profiles.memory_policy_ref,"SERVER_MEMORY_POLICY_SPEC.json");
assert.equal(tools.memory_policy_ref,"SERVER_MEMORY_POLICY_SPEC.json");
for(const scope of ["agent_state","memory_entries","task_entries"])assert.ok(mem.memory_scopes[scope]);
const expected={memory_get_state:["agent_state","read"],memory_set_state:["agent_state","state_update"],memory_search:["memory_entries","search"],memory_save:["memory_entries","write"],memory_get_tasks:["task_entries","task_list"],memory_create_task:["task_entries","task_create"]};
for(const [name,[scope,op]] of Object.entries(expected)){
  assert.equal(mem.tool_bindings[name].scope,scope);
  assert.equal(mem.tool_bindings[name].operation_class,op);
  assert.equal(tools.tool_catalog[name].operation_class,op);
  assert.equal(tools.tool_catalog[name].memory_policy_ref,"SERVER_MEMORY_POLICY_SPEC.json");
}
for(const s of Object.values(pub.surfaces))assert.deepEqual(s.allowed_memory_scopes,[]);
assert.deepEqual(tests.surfaces.public.allowed_memory_scopes,[]);
assert.deepEqual(tests.surfaces.authenticated.allowed_memory_scopes,["agent_state","memory_entries","task_entries"]);
let bad=JSON.parse(JSON.stringify(pub));
bad.surfaces.public.allowed_memory_scopes=["memory_entries"];
let result=validateProfileObject(bad,{expectedName:"public",profilePath:"profiles/public.json"});
assert.equal(result.ok,false);
assert.ok(result.errors.join(";").includes("must be empty on public surface"));
bad=JSON.parse(JSON.stringify(tests));
bad.surfaces.authenticated.allowed_memory_scopes=["unknown_memory_scope"];
result=validateProfileObject(bad,{expectedName:"tests",profilePath:"profiles/tests.json"});
assert.equal(result.ok,false);
assert.ok(result.errors.join(";").includes("unknown memory scope"));
assert.equal(Boolean(root.cli?.parameters?.["--memory-policy"]),false);
console.log("smoke_memory_policy_spec ok");
