"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
function read(p){return JSON.parse(fs.readFileSync(p,"utf8"));}
const root=read("SERVER_SPEC.json");
const db=read("SERVER_DATABASE_POLICY_SPEC.json");
const res=read("SERVER_RESOURCE_POLICY_SPEC.json");
const authz=read("SERVER_AUTHZ_DECISION_SPEC.json");
const mem=read("SERVER_MEMORY_POLICY_SPEC.json");
const net=read("SERVER_NETWORK_POLICY_SPEC.json");
const profiles=read("SERVER_PROFILES_SPEC.json");
const tools=read("SERVER_TOOLS_SPEC.json");
const pub=read("profiles/public.json");
const tests=read("profiles/tests.json");
const { validateProfileObject } = require("../src/profile_schema_validator");
assert.equal(db.schema_version,"mcp-tests-server-database-policy-spec-v1");
assert.equal(db.runtime_enforced,false);
assert.equal(db.current_database_runtime.direct_mcp_database_tools_present,false);
assert.equal(db.current_database_runtime.raw_sql_tools_present,false);
assert.equal(db.tool_policy.direct_database_mcp_tools_allowed_now,false);
assert.equal(db.tool_policy.raw_sql_tool_forbidden,true);
assert.equal(db.safety_rules.no_cli_extension,true);
assert.equal(db.safety_rules.public_surface_database_access_forbidden,true);
assert.equal(db.safety_rules.migrations_require_dry_run_plan_receipt_and_operator_approval,true);
assert.equal(root.spec_refs.database_policy,"SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(authz.database_policy_ref,"SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(res.database_policy_ref,"SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(mem.database_policy_ref,"SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(net.database_policy_ref,"SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(profiles.server_profiles.database_policy_ref,"SERVER_DATABASE_POLICY_SPEC.json");
assert.equal(tools.database_policy_ref,"SERVER_DATABASE_POLICY_SPEC.json");
for(const scope of ["state_store","memory_store","network_cache_store","plugin_visibility_store","audit_receipt_store","operator_config_store","schema_migration_store"])assert.ok(db.database_scopes[scope]);
for(const surf of Object.values(pub.surfaces))assert.deepEqual(surf.allowed_database_scopes,[]);
for(const surf of Object.values(tests.surfaces))assert.deepEqual(surf.allowed_database_scopes,[]);
let bad=JSON.parse(JSON.stringify(pub));
bad.surfaces.public.allowed_database_scopes=["memory_store"];
let result=validateProfileObject(bad,{expectedName:"public",profilePath:"profiles/public.json"});
assert.equal(result.ok,false);
assert.ok(result.errors.join(";").includes("must be empty on public surface"));
bad=JSON.parse(JSON.stringify(tests));
bad.surfaces.authenticated.allowed_database_scopes=["unknown_database_scope"];
result=validateProfileObject(bad,{expectedName:"tests",profilePath:"profiles/tests.json"});
assert.equal(result.ok,false);
assert.ok(result.errors.join(";").includes("unknown database scope"));
assert.equal(Boolean(root.cli?.parameters?.["--database-policy"]),false);
console.log("smoke_stage12_database_policy_spec ok");
