"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const ROOT=path.resolve(__dirname,"..");
const read=(p)=>fs.readFileSync(path.join(ROOT,p),"utf8");
const json=(p)=>JSON.parse(read(p));
const matrix=json("SERVER_POLICY_COVERAGE_MATRIX_SPEC.json");
const readiness=read("_workflow/READINESS.md");
const roadmap=read("_workflow/ROADMAP.md");
const state=json("_workflow/state.json");
const active=read("_workflow/ACTIVE_WORKFLOW_INDEX.md");
const protocol=json("SERVER_PROTOCOL_CAPABILITY_SPEC.json");
const required=matrix.policies.filter((p)=>p.required!==false);
assert.equal(required.filter((p)=>p.status==="implemented").length,20);
assert.equal(required.filter((p)=>p.status!=="implemented").length,4);
assert.equal(required.filter((p)=>p.status==="critical_specified").length,0);
assert.equal(required.filter((p)=>p.critical&&p.status!=="implemented").length,0);
assert.match(readiness,/\| POL-1 \| Policy coverage convergence \| 3\/4 \|/);
assert.match(readiness,/POL-1A-PROMPT-CONTENT/);
assert.match(readiness,/Repository target coverage is `20\/24` implemented/);
assert.match(readiness,/loaded OAuth21 runtime remains at the accepted `16\/24` baseline/);
const runtimeId=state.current_runtime_truth.oauth21_3008.server_start_id;
assert.match(runtimeId,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);
assert.ok(active.includes(`server_start_id = ${runtimeId}`));
assert.equal(state.current_runtime_truth.oauth21_3008.restart_required_now,true);
assert.equal(state.policy_coverage_matrix.repo_implemented_required,"20/24");
assert.equal(state.policy_coverage_matrix.live_implemented_required,"16/24");
assert.match(readiness,/All `6\/6` critical policies remain implemented/);
assert.match(active,/promotion_allowed=false/);
assert.match(roadmap,/Production MRTR runtime — live accepted/);
assert.match(roadmap,/Historical POL-1A process-MRTR acceptance/);
assert.ok(roadmap.indexOf("POL-1B") < roadmap.indexOf("COMP-1A"));
assert.equal(protocol.release_2026_07_28.classification["SEP-2322"].s,"live_optional_module");
assert.equal(protocol.deployment_and_activation_queue.find((entry)=>entry.sep==="SEP-2322").runtime_status,"live_accepted");
assert.equal(state.workflow_progress_markers.next_primary,"pol-1b");
assert.equal(state.workflow_progress_markers.next_secondary,"pol-1c");
assert.match(active,/POL-1A-PROMPT-CONTENT/);
assert.doesNotMatch(active,/`next_primary = pol-1a-prompt-content`/);
assert.match(active,/Completed production `MRTR` on August 18, 2026/);
console.log("smoke_policy_readiness_current_truth ok");
