"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const ROOT=path.resolve(__dirname,"..");
const toolsSpec=JSON.parse(fs.readFileSync(path.join(ROOT,"SERVER_TOOLS_SPEC.json"),"utf8"));
const authorized=toolsSpec.surface_classes.authorized_mcp_tools.tools;
assert.ok(Array.isArray(authorized));
assert.equal(authorized.length,32);
assert.equal(Object.hasOwn(toolsSpec.surface_classes,"non_public_mcp_tools"),false);
const authorizedJs=fs.readdirSync(path.join(ROOT,"tools","authorized")).filter((n)=>n.endsWith(".js")).map((n)=>n.replace(/\.js$/,""));
assert.deepEqual(authorizedJs.sort(),authorized.slice().sort());
const internalJs=fs.readdirSync(path.join(ROOT,"tools","internal")).filter((n)=>n.endsWith(".js"));
assert.deepEqual(internalJs,[]);
const loader=fs.readFileSync(path.join(ROOT,"src","tool_loader.js"),"utf8");
assert.ok(loader.includes("../tools/authorized/"));
assert.equal(loader.includes("../tools/internal/"),false);
assert.ok(loader.includes("groupEnabled(\"authorized\")"));
assert.equal(loader.includes("groupEnabled(\"internal\")"),false);
const server=fs.readFileSync(path.join(ROOT,"server.js"),"utf8");
const optionalAssembly=fs.readFileSync(path.join(ROOT,"src","runtime","optional_tools_assembly.js"),"utf8");
assert.equal(server.includes("./tools/authorized/test_mcp_runtime_status"), false);
assert.equal(server.includes("./tools/authorized/observability_status"), false);
assert.ok(optionalAssembly.includes("../../tools/authorized/test_mcp_runtime_status"));
assert.ok(optionalAssembly.includes("../../tools/authorized/observability_status"));
assert.equal(server.includes("./tools/internal/"),false);
const testsProfile=JSON.parse(fs.readFileSync(path.join(ROOT,"profiles","tests.json"),"utf8"));
assert.deepEqual(testsProfile.surfaces.authenticated.optional_tool_groups,["public","authorized"]);
const publicProfile=JSON.parse(fs.readFileSync(path.join(ROOT,"profiles","public.json"),"utf8"));
assert.deepEqual(publicProfile.surfaces.public.optional_tool_groups,["public"]);
const { loadOptionalTools }=require("../src/tool_loader");
const { createTestMcpRuntimeStatusTool }=require("../tools/authorized/test_mcp_runtime_status");
const { createObservabilityStatusTool }=require("../tools/authorized/observability_status");
const tools=loadOptionalTools({profile:"internal",authPolicy:{mode:"access",requiresAuth:true},serverProfileConfig:{surface:testsProfile.surfaces.authenticated},createRuntimeStatusTool:()=>createTestMcpRuntimeStatusTool(()=>({status:"ok"})),createObservabilityStatusTool:()=>createObservabilityStatusTool({auditLogPath:"_logs/.mcp-tests-audit.jsonl"})});
for(const name of authorized)assert.ok(tools.some((tool)=>tool.name===name),`missing loaded authorized tool ${name}`);
console.log("smoke_stage12_step38n_authorized_internal_facade_split ok");
