"use strict";
const assert=require("node:assert/strict");
const {McpSession}=require("../src/runtime/session");
const {encodeSseEvent}=require("../src/runtime/sse_response");
function res(){return{chunks:[],write(x){this.chunks.push(String(x));},body(){return this.chunks.join("");}}}
const s=new McpSession({id:"mcp_test",protocolVersion:"2025-06-18"});
const e1=encodeSseEvent({event:"message",data:{jsonrpc:"2.0",method:"notifications/a"}});
const e2=encodeSseEvent({event:"message",data:{jsonrpc:"2.0",method:"notifications/b"}});
s.enqueueOutbound(e1);
s.enqueueOutbound(e2);
assert.equal(s.outboundQueue.length,2);
const r=res();
s.attachStream(r);
assert.equal(s.sseRes,r);
assert.equal(s.outboundQueue.length,0);
assert.ok(r.body().includes("notifications/a"));
assert.ok(r.body().includes("notifications/b"));
s.enqueueOutbound(encodeSseEvent({event:"message",data:{jsonrpc:"2.0",method:"notifications/c"}}));
assert.equal(s.outboundQueue.length,0);
assert.ok(r.body().includes("notifications/c"));
s.detachStream(r);
assert.equal(s.sseRes,null);
s.enqueueOutbound(encodeSseEvent({event:"message",data:{jsonrpc:"2.0",method:"notifications/d"}}));
assert.equal(s.outboundQueue.length,1);
console.log("smoke_stage12_outbound_queue ok");
