"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const ROOT = path.resolve(__dirname, "..");
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8");
const record = read("_workflow/operator_decisions/s10a_manual_live_probe_contract.md");
assert.ok(record.includes("Status: PREPARED / MANUAL EXECUTION REQUIRED / TOOL-LAYER BLOCKED"));
assert.ok(record.includes("does not claim GREEN runtime completion"));
assert.ok(record.includes("_workflow/scripts/s10_manual_sessionless_probe_stub.js"));
assert.ok(record.includes("No connector refresh"));
assert.ok(record.includes("connector route migration"));
assert.ok(record.includes("public 3009 start"));
assert.ok(record.includes("OAuth21 3008 restart"));
const stubPath = path.join(ROOT, "_workflow/scripts/s10_manual_sessionless_probe_stub.js");
assert.ok(fs.existsSync(stubPath));
const stub = read("_workflow/scripts/s10_manual_sessionless_probe_stub.js");
assert.ok(stub.includes("s10a_manual_sessionless_probe_stub"));
assert.ok(stub.includes("manual_execution_required"));
const self = spawnSync(process.execPath, [stubPath, "--self-test"], { cwd: ROOT, encoding: "utf8" });
assert.equal(self.status, 0, self.stderr || self.stdout);
const selfJson = JSON.parse(self.stdout);
assert.equal(selfJson.ok, true);
assert.equal(selfJson.network, false);
const manifest = JSON.parse(read("_tests/run_all_smoke_scripts.json"));
assert.ok(manifest.includes("_tests/smoke_s10a_manual_live_probe_contract.js"));
console.log("smoke_s10a_manual_live_probe_contract ok");
