"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
function read(rel) { return fs.readFileSync(path.join(ROOT, rel), "utf8"); }
const inventory = JSON.parse(read("_workflow/sessionless_inventory.json"));
const record = read("_workflow/operator_decisions/explicit_state_handle_design_rules.md");
const target = inventory.target_selection_readiness;
const rules = target.s3_explicit_state_handle_design_rules;
assert.ok(record.includes("Historical next step at that time: proceed to the S4 parallel draft/sessionless runtime prototype behind a non-default route or mode"));
assert.ok(record.includes("This is no longer the active queue; the current target authority is the single-route no-SSE plan on surviving `/mcp`."));
assert.ok(rules);
assert.equal(rules.status, "prepared_no_runtime_change");
assert.equal(rules.source_of_truth, "_workflow/sessionless_inventory.json");
assert.equal(rules.guard, "_tests/smoke_explicit_state_handle_design_rules.js");
assert.equal(rules.protocol_boundary, "tool_design_pattern_not_wire_protocol_feature");
assert.equal(rules.current_runtime_behavior_changed, false);
assert.equal(rules.connector_refresh_required_now, false);
assert.equal(rules.runtime_restart_required_now, false);
assert.equal(rules.schema_change_required_now, false);
assert.equal(rules.public_3009_start_required_now, false);
assert.equal(fs.existsSync(path.join(ROOT, "src/sessionless_target_selection_readiness.js")), false);
assert.equal(Object.prototype.hasOwnProperty.call(target, "readiness_module"), false);
assert.equal(rules.handle_model.handle_is_secret, true);
assert.equal(rules.handle_model.min_entropy_bits, 128);
assert.equal(rules.handle_model.parse_policy, "do_not_encode_authorization_or_business_state_in_handle");
assert.ok(rules.handle_model.allowed_handle_kinds.includes("task"));
assert.ok(rules.handle_model.allowed_handle_kinds.includes("subscription_cursor"));
for (const field of ["handle_id_hash","kind","owner_subject_hash","client_id_hash","audience","profile","scopes","issued_at","expires_at","status","state_version","state_payload_ref"]) assert.ok(rules.handle_model.required_record_fields.includes(field), field);
assert.equal(rules.authorization_rules.possession_is_not_authorization, true);
assert.equal(rules.authorization_rules.validate_on_every_use, true);
assert.equal(rules.authorization_rules.reject_cross_profile_use, true);
assert.equal(rules.authorization_rules.reject_missing_or_weaker_scope, true);
assert.equal(rules.authorization_rules.allow_delegation, false);
for (const field of ["oauth_subject","oauth_client_id","audience","profile","authorized_scopes"]) assert.ok(rules.authorization_rules.bind_to.includes(field), field);
assert.equal(rules.lifecycle_rules.create_requires_authorized_tool_result, true);
assert.equal(rules.lifecycle_rules.default_ttl_ms, 1800000);
assert.equal(rules.lifecycle_rules.max_ttl_ms, 86400000);
assert.equal(rules.lifecycle_rules.refresh_requires_reauthorization, true);
assert.equal(rules.lifecycle_rules.destroy_required_for_user_visible_long_lived_state, true);
assert.equal(rules.lifecycle_rules.expired_or_revoked_handles_must_fail_closed, true);
assert.equal(rules.tool_contract_rules.handles_returned_in_structured_content_only, true);
assert.equal(rules.tool_contract_rules.raw_handles_never_in_logs_or_human_text, true);
assert.equal(rules.tool_contract_rules.handle_arguments_must_be_named, "state_handle");
assert.equal(rules.audit_redaction_rules.raw_handle_forbidden, true);
assert.equal(rules.audit_redaction_rules.audit_handle_hash_only, true);
assert.equal(rules.audit_redaction_rules.forbid_first_last_character_logging, true);
assert.equal(rules.audit_redaction_rules.redact_payload_ref, true);
for (const key of ["invalid","expired","revoked","not_found","unauthorized","scope_denied","kind_mismatch"]) assert.match(rules.error_contract[key], /^state_handle_/);
assert.equal(rules.s4_readiness_gate.runtime_code_required_for_s4, true);
assert.equal(rules.s4_readiness_gate.implement_behind_non_default_route_or_mode, true);
assert.equal(rules.s4_readiness_gate.keep_current_oauth21_3008_stable_route_unchanged, true);
assert.equal(rules.s4_readiness_gate.connector_refresh_before_s4, false);
assert.equal(rules.s4_readiness_gate.restart_3008_after_runtime_code, true);
console.log("smoke_explicit_state_handle_design_rules ok");
