"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
function read(rel) { return fs.readFileSync(path.join(ROOT, rel), "utf8"); }
const inventory = JSON.parse(read("_workflow/sessionless_inventory.json"));
const readiness = inventory.target_selection_readiness;
assert.ok(readiness);
assert.equal(readiness.status, "selected_parallel_track_stable_mcp_preserved");
assert.equal(readiness.record, "_workflow/operator_decisions/sessionless_target_selection_decision.md");
assert.equal(readiness.source_of_truth, "_workflow/sessionless_inventory.json");
assert.equal(readiness.guard, "_tests/smoke_sessionless_target_selection_readiness.js");
assert.equal(readiness.truth_consolidation, "inventory_authoritative_no_src_projection");
assert.equal(Object.prototype.hasOwnProperty.call(readiness, "readiness_module"), false);
assert.equal(inventory.source_review.includes("src/sessionless_target_selection_readiness.js"), false);
assert.equal(fs.existsSync(path.join(ROOT, "src/sessionless_target_selection_readiness.js")), false);
assert.equal(readiness.recommended_target, "parallel_draft_sessionless_prototype_while_keeping_stable_connector_current");
assert.equal(readiness.selected_target, "parallel_draft_sessionless_prototype_while_keeping_stable_connector_current");
assert.equal(readiness.historical_transition_decision_only, true);
assert.equal(readiness.superseded_as_end_state_by, "_workflow/operator_decisions/single_route_no_sse_streamable_http_target_plan.md");
assert.equal(readiness.stable_connector_current_target, "keep_current_oauth21_3008_stable_compatible_route");
assert.equal(readiness.full_switch_now, "not_recommended");
assert.equal(readiness.do_not_remove_current_session_code, true);
assert.equal(readiness.connector_refresh_required_now, false);
assert.equal(readiness.runtime_restart_required_now, false);
assert.equal(readiness.schema_change_required_now, false);
assert.equal(readiness.public_3009_start_required_now, false);
assert.equal(readiness.operator_selection_required_before_runtime_prototype, false);
const rules = readiness.explicit_state_handle_rules;
assert.equal(rules.handles_are_tool_design_pattern_not_protocol_feature, true);
assert.equal(rules.handles_are_ordinary_tool_arguments_and_structured_content_fields, true);
assert.equal(rules.opaque_ids_required, true);
assert.equal(inventory.active_target_contract.single_route_only, true);
assert.equal(inventory.active_target_contract.sse_allowed_in_end_state, false);
console.log("smoke_sessionless_target_selection_readiness ok");
