"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const ROOT=path.resolve(__dirname,"..");
const read=(p)=>fs.readFileSync(path.join(ROOT,p),"utf8");
const json=(p)=>JSON.parse(read(p));
const matrix=json("SERVER_POLICY_COVERAGE_MATRIX_SPEC.json");
const readiness=read("_workflow/READINESS.md");
const roadmap=read("_workflow/ROADMAP.md");
const state=json("_workflow/state.json");
const active=read("_workflow/ACTIVE_WORKFLOW_INDEX.md");
const protocol=json("SERVER_PROTOCOL_CAPABILITY_SPEC.json");
const required=matrix.policies.filter((p)=>p.required!==false);
assert.equal(required.filter((p)=>p.status==="implemented").length,14);
assert.equal(required.filter((p)=>p.status!=="implemented").length,10);
assert.equal(required.filter((p)=>p.status==="critical_specified").length,2);
assert.match(readiness,/\| POL-1 \| Policy coverage convergence \| 2\/4 \|/);
assert.match(readiness,/POL-1A-CONSENT/);
assert.match(readiness,/production MRTR \(`SEP-2322`\) is now live-loaded/);
assert.doesNotMatch(readiness,/COMP-1.*only component still externally event-gated/);
assert.match(roadmap,/Production MRTR runtime — live accepted/);
assert.match(roadmap,/POL-1A-CONSENT/);
assert.ok(roadmap.indexOf("POL-1A-CONSENT") < roadmap.indexOf("COMP-1A"));
assert.equal(protocol.release_2026_07_28.classification["SEP-2322"].s,"live_optional_module");
assert.equal(protocol.deployment_and_activation_queue.find((entry)=>entry.sep==="SEP-2322").runtime_status,"live_accepted");
assert.equal(state.workflow_progress_markers.next_primary,"pol-1a-consent-boundary");
assert.equal(state.workflow_progress_markers.next_secondary,"pol-1a-prompt-content");
assert.match(active,/pol-1a-consent-boundary/);
assert.match(active,/pol-1a-prompt-content/);
assert.match(active,/Completed production `MRTR` on August 18, 2026/);
console.log("smoke_policy_readiness_current_truth ok");
