const READ_ONLY_TOOL_REGISTRY_ANNOTATIONS = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false,
};

const TOOL_NAME_INPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["tool"],
  properties: {
    tool: {
      type: "string",
      minLength: 1,
      maxLength: 120,
      pattern: "^[a-z][a-z0-9_]{1,80}$",
    },
  },
};

const TOOL_OPERATION_INPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["tool", "operation"],
  properties: {
    tool: TOOL_NAME_INPUT_SCHEMA.properties.tool,
    operation: {
      type: "string",
      minLength: 1,
      maxLength: 80,
      pattern: "^[a-z_][a-z0-9_]{1,79}$",
    },
  },
};

const TOOL_EXECUTE_INPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["tool", "operation"],
  properties: {
    tool: TOOL_NAME_INPUT_SCHEMA.properties.tool,
    operation: TOOL_OPERATION_INPUT_SCHEMA.properties.operation,
    execution_mode: {
      type: "string",
      enum: ["simulation"],
      default: "simulation",
    },
  },
};

const EMPTY_INPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [],
  properties: {},
};

const TOOL_REGISTRY_SUMMARY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "tool",
    "source",
    "enabled",
    "title",
    "description",
    "surface_class",
    "tool_category",
    "resource_class",
    "operation_class",
    "auth_required",
    "public_safe",
    "read_only",
    "open_world",
    "uses_fs",
    "uses_network",
    "fs_scope",
  ],
  properties: {
    tool: { type: "string" },
    source: { type: "string" },
    enabled: { type: "boolean" },
    title: { type: "string" },
    description: { type: "string" },
    surface_class: { type: "string" },
    tool_category: { type: "string" },
    resource_class: { type: "string" },
    operation_class: { type: "string" },
    auth_required: { type: "boolean" },
    public_safe: { type: "boolean" },
    read_only: { type: "boolean" },
    open_world: { type: "boolean" },
    uses_fs: { type: "boolean" },
    uses_network: { type: "boolean" },
    fs_scope: { type: "string" },
  },
};

const DESCRIPTOR_SUMMARY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["name", "title", "description", "input_schema_type", "output_schema_present", "annotation_summary"],
  properties: {
    name: { type: ["string", "null"] },
    title: { type: ["string", "null"] },
    description: { type: ["string", "null"] },
    input_schema_type: { type: ["string", "null"] },
    output_schema_present: { type: "boolean" },
    annotation_summary: {
      type: ["object", "null"],
      additionalProperties: false,
      required: ["readOnlyHint", "destructiveHint", "idempotentHint", "openWorldHint"],
      properties: {
        readOnlyHint: { type: "boolean" },
        destructiveHint: { type: "boolean" },
        idempotentHint: { type: "boolean" },
        openWorldHint: { type: "boolean" },
      },
    },
  },
};

const POLICY_SUMMARY_SCHEMA = {
  type: ["object", "null"],
  additionalProperties: false,
  required: [
    "profile_allowed",
    "read_only",
    "destructive",
    "open_world",
    "uses_network",
    "uses_fs",
    "fs_scope",
    "auth_required",
    "public_safe",
  ],
  properties: {
    profile_allowed: { type: "array", items: { type: "string" } },
    read_only: { type: "boolean" },
    destructive: { type: "boolean" },
    open_world: { type: "boolean" },
    uses_network: { type: "boolean" },
    uses_fs: { type: "boolean" },
    fs_scope: { type: "string" },
    auth_required: { type: "boolean" },
    public_safe: { type: "boolean" },
  },
};

const CATALOG_SUMMARY_SCHEMA = {
  type: ["object", "null"],
  additionalProperties: false,
  required: [
    "name",
    "surface_class",
    "tool_category",
    "resource_class",
    "operation_class",
    "resource_policy_refs",
    "memory_policy_ref",
    "network_policy_ref",
    "database_policy_ref",
    "plugin_visibility_policy_ref",
    "audit_required",
    "auth_required",
    "public_safe",
  ],
  properties: {
    name: { type: ["string", "null"] },
    surface_class: { type: ["string", "null"] },
    tool_category: { type: ["string", "null"] },
    resource_class: { type: ["string", "null"] },
    operation_class: { type: ["string", "null"] },
    resource_policy_refs: { type: "array", items: { type: "string" } },
    memory_policy_ref: { type: ["string", "null"] },
    network_policy_ref: { type: ["string", "null"] },
    database_policy_ref: { type: ["string", "null"] },
    plugin_visibility_policy_ref: { type: ["string", "null"] },
    audit_required: { type: "boolean" },
    auth_required: { type: ["boolean", "null"] },
    public_safe: { type: ["boolean", "null"] },
  },
};

const PLAN_STEP_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["order", "action", "status"],
  properties: {
    order: { type: "integer", minimum: 1 },
    action: { type: "string" },
    status: { type: "string" },
  },
};

const EXECUTE_STEP_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["order", "action", "status", "simulated"],
  properties: {
    order: { type: "integer", minimum: 1 },
    action: { type: "string" },
    status: { type: "string" },
    simulated: { type: "boolean" },
  },
};

const TOOL_REGISTRY_STATUS_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "registry_version",
    "registry_id",
    "tool_count",
    "enabled_tool_count",
    "tools",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    registry_version: { type: "string" },
    registry_id: { type: "string" },
    tool_count: { type: "integer", minimum: 0 },
    enabled_tool_count: { type: "integer", minimum: 0 },
    tools: { type: "array", items: TOOL_REGISTRY_SUMMARY_SCHEMA },
  },
};

const TOOL_REGISTRY_GET_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "registry_version",
    "registry_id",
    "tool",
    "found",
    "enabled",
    "metadata",
    "descriptor_summary",
    "tool_policy_summary",
    "catalog_summary",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    registry_version: { type: "string" },
    registry_id: { type: "string" },
    tool: { type: "string" },
    found: { type: "boolean" },
    enabled: { type: "boolean" },
    metadata: { type: ["object", "null"], additionalProperties: false, properties: TOOL_REGISTRY_SUMMARY_SCHEMA.properties, required: TOOL_REGISTRY_SUMMARY_SCHEMA.required },
    descriptor_summary: DESCRIPTOR_SUMMARY_SCHEMA,
    tool_policy_summary: POLICY_SUMMARY_SCHEMA,
    catalog_summary: CATALOG_SUMMARY_SCHEMA,
  },
};

const TOOL_REGISTRY_VALIDATE_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "registry_id",
    "tool",
    "found",
    "enabled",
    "allowed",
    "reason",
    "metadata",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    registry_id: { type: "string" },
    tool: { type: "string" },
    found: { type: "boolean" },
    enabled: { type: "boolean" },
    allowed: { type: "boolean" },
    reason: { type: ["string", "null"] },
    metadata: { type: ["object", "null"], additionalProperties: false, properties: TOOL_REGISTRY_SUMMARY_SCHEMA.properties, required: TOOL_REGISTRY_SUMMARY_SCHEMA.required },
  },
};

const TOOL_REGISTRY_POLICY_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "registry_version",
    "registry_id",
    "tool",
    "found",
    "enabled",
    "allowed",
    "reason",
    "descriptor_summary",
    "tool_policy_summary",
    "catalog_summary",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    registry_version: { type: "string" },
    registry_id: { type: "string" },
    tool: { type: "string" },
    found: { type: "boolean" },
    enabled: { type: "boolean" },
    allowed: { type: "boolean" },
    reason: { type: ["string", "null"] },
    descriptor_summary: DESCRIPTOR_SUMMARY_SCHEMA,
    tool_policy_summary: POLICY_SUMMARY_SCHEMA,
    catalog_summary: CATALOG_SUMMARY_SCHEMA,
  },
};

const TOOL_REGISTRY_PREFLIGHT_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "registry_id",
    "tool",
    "operation",
    "found",
    "enabled",
    "allowed",
    "reason",
    "allowed_operations",
    "tool_policy_summary",
    "catalog_summary",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    registry_id: { type: "string" },
    tool: { type: "string" },
    operation: { type: "string" },
    found: { type: "boolean" },
    enabled: { type: "boolean" },
    allowed: { type: "boolean" },
    reason: { type: ["string", "null"] },
    allowed_operations: { type: "array", items: { type: "string" } },
    tool_policy_summary: POLICY_SUMMARY_SCHEMA,
    catalog_summary: CATALOG_SUMMARY_SCHEMA,
  },
};

const TOOL_REGISTRY_PLAN_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "execution_enabled",
    "registry_id",
    "tool",
    "operation",
    "found",
    "enabled",
    "allowed",
    "plan_ready",
    "reason",
    "steps",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    execution_enabled: { type: "boolean" },
    registry_id: { type: "string" },
    tool: { type: "string" },
    operation: { type: "string" },
    found: { type: "boolean" },
    enabled: { type: "boolean" },
    allowed: { type: "boolean" },
    plan_ready: { type: "boolean" },
    reason: { type: ["string", "null"] },
    steps: { type: "array", items: PLAN_STEP_SCHEMA },
  },
};

const TOOL_REGISTRY_EXECUTE_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "success",
    "error",
    "status",
    "connector_safe",
    "dispatch_enabled",
    "execution_enabled",
    "simulated_execution",
    "execution_mode",
    "execution_id",
    "plan_hash",
    "registry_id",
    "tool",
    "operation",
    "found",
    "enabled",
    "allowed",
    "plan_ready",
    "reason",
    "steps_count",
    "simulated_steps",
  ],
  properties: {
    success: { type: "boolean" },
    error: { type: "string" },
    status: { type: "string" },
    connector_safe: { type: "boolean" },
    dispatch_enabled: { type: "boolean" },
    execution_enabled: { type: "boolean" },
    simulated_execution: { type: "boolean" },
    execution_mode: { type: "string" },
    execution_id: { type: "string" },
    plan_hash: { type: "string" },
    registry_id: { type: "string" },
    tool: { type: "string" },
    operation: { type: "string" },
    found: { type: "boolean" },
    enabled: { type: "boolean" },
    allowed: { type: "boolean" },
    plan_ready: { type: "boolean" },
    reason: { type: ["string", "null"] },
    steps_count: { type: "integer", minimum: 0 },
    simulated_steps: { type: "array", items: EXECUTE_STEP_SCHEMA },
  },
};

module.exports = {
  CATALOG_SUMMARY_SCHEMA,
  DESCRIPTOR_SUMMARY_SCHEMA,
  EMPTY_INPUT_SCHEMA,
  POLICY_SUMMARY_SCHEMA,
  READ_ONLY_TOOL_REGISTRY_ANNOTATIONS,
  TOOL_EXECUTE_INPUT_SCHEMA,
  TOOL_NAME_INPUT_SCHEMA,
  TOOL_OPERATION_INPUT_SCHEMA,
  TOOL_REGISTRY_EXECUTE_OUTPUT_SCHEMA,
  TOOL_REGISTRY_GET_OUTPUT_SCHEMA,
  TOOL_REGISTRY_PLAN_OUTPUT_SCHEMA,
  TOOL_REGISTRY_POLICY_OUTPUT_SCHEMA,
  TOOL_REGISTRY_PREFLIGHT_OUTPUT_SCHEMA,
  TOOL_REGISTRY_STATUS_OUTPUT_SCHEMA,
  TOOL_REGISTRY_SUMMARY_SCHEMA,
  TOOL_REGISTRY_VALIDATE_OUTPUT_SCHEMA,
};
