"use strict";
const assert=require("node:assert/strict");
const {McpSession}=require("../../src/runtime/session");
function res(){return{chunks:[],write(x){this.chunks.push(String(x));},body(){return this.chunks.join("");}}}
const session=new McpSession({id:"mcp_replay",protocolVersion:"2025-06-18",maxReplayEvents:3});
const initial=res();session.attachStream(initial);
session.enqueueOutbound("event: message\ndata: one\n\n");
session.enqueueOutbound("event: message\ndata: two\n\n");
session.enqueueOutbound("event: message\ndata: three\n\n");
assert.equal(session.replayBuffer.length,3);
assert.ok(session.replayBuffer[0].event.startsWith("id: 1\n"));
session.detachStream(initial);
const r=res();session.attachStream(r,{lastEventId:"1"});
assert.ok(r.body().includes("id: 2"));
assert.ok(r.body().includes("data: two"));
assert.ok(r.body().includes("id: 3"));
assert.ok(!r.body().includes("data: one"));
session.detachStream(r);
const active=res();session.attachStream(active);
session.enqueueOutbound("event: message\ndata: four\n\n");
assert.ok(active.body().includes("id: 4"));
assert.ok(active.body().includes("data: four"));
session.enqueueOutbound("event: message\ndata: five\n\n");
session.enqueueOutbound("event: message\ndata: six\n\n");
assert.equal(session.replayBuffer.length,3);
assert.equal(session.replayBuffer[0].id,4);
session.detachStream(active);
const late=res();session.attachStream(late,{lastEventId:"4"});
assert.ok(!late.body().includes("data: four"));
assert.ok(late.body().includes("data: five"));
assert.ok(late.body().includes("data: six"));
console.log("smoke_sse_resumability ok");
