const MECHANISM_PARITY_MATRIX_VERSION = "test-mcp-mechanism-endurance-v2";

const MECHANISM_ENDURANCE_MATRIX = [
  {
    mechanism: "index_mechanisms",
    source_server: "GPT MCP index subsystem",
    source_modules: ["core/tools_index.js"],
    source_tools: ["index_status", "build_index", "search_index", "search_index_context", "collect_context", "collect_romionsim_context"],
    source_methods: [
      "index freshness reporting",
      "bounded context retrieval",
      "source authority separation",
      "deterministic rebuild accounting",
      "query-result traceability",
    ],
    endurance_status: "covered",
    exposure_decision: "covered_by_existing_runtime_and_workflow_probes",
    endurance_probes: ["search", "fetch", "_tests/smoke_stage12_step37a_index_source_authority.js"],
    negative_controls: ["stale source authority guard", "bounded fetch/context behavior"],
    hold_reason: "No new runtime tool is required before Step39; endurance is tested through existing search/fetch and source-authority guards.",
    required_next_step: "Keep source-authority and freshness probes current when index semantics change.",
  },
  {
    mechanism: "filesystem_mechanisms",
    source_server: "GPT MCP filesystem subsystem",
    source_modules: ["core/tools_fs.js", "core/filesystem/patch_tools.js"],
    source_tools: ["read_file", "read_file_lines", "read_file_chunk", "write_file", "append_file", "copy_path", "move_path", "delete_path", "restore_path", "edit_file_patch", "inventory_tree"],
    source_methods: [
      "safe path normalization",
      "bounded reads",
      "line/chunk semantics",
      "protected path denial",
      "backup-before-overwrite discipline",
      "soft delete with restore metadata",
    ],
    endurance_status: "covered",
    exposure_decision: "runtime_read_only_workflow_mutation_only",
    endurance_probes: [
      "fs_list_public",
      "fs_get_public_info",
      "fs_read_public_text",
      "fs_read_public_lines",
      "fs_read_public_chunk",
      "_tests/smoke_stage3_fs.js",
      "_tests/smoke_stage5_1_fs_streaming.js",
      "_tests/smoke_stage8_54_io_safety_policy.js",
      "_tests/smoke_stage8_55_io_safety_active_controls.js",
    ],
    negative_controls: ["public runtime remains read-only", "path traversal and protected path controls", "workflow-only mutation controls"],
    hold_reason: "Write/move/delete parity should not become connector-visible before Step39; existing read-only runtime plus workflow controls cover the relevant endurance boundary.",
    required_next_step: "Only add mutation probes inside workflow harnesses if mutation policy changes.",
  },
  {
    mechanism: "science_data_introspection_mechanisms",
    source_server: "GPT MCP science data subsystem",
    source_modules: ["core/science_tools.js"],
    source_tools: ["fits_info", "hdf5_info", "table_profile"],
    source_methods: [
      "bounded scientific/binary metadata introspection",
      "format-aware safe parsing",
      "header/structure extraction without full content dump",
      "safe corrupt-input failure envelope",
      "explicit caps for expensive scans",
    ],
    endurance_status: "on_hold",
    exposure_decision: "defer_probe_no_runtime_tool_before_step39",
    endurance_probes: [],
    negative_controls: [],
    hold_reason: "No current Step39-critical path depends on FITS/HDF5/table profiling semantics. Adding probes now would expand scope without reducing immediate runtime or connector risk.",
    required_next_step: "Before any science-data feature work, add fixture-only bounded introspection probes and corrupt/oversized-input negative controls; keep the science-data runtime surface non-public unless a later stage explicitly authorizes it.",
  },
  {
    mechanism: "connector_safe_code_mechanisms",
    source_server: "GPT MCP connector-safe code subsystem",
    source_modules: ["core/code_tools_safe.js"],
    source_tools: ["code_symbols", "code_dependencies", "code_audit", "code_impact"],
    source_methods: [
      "read-only structural code sampling",
      "bounded dependency graphing",
      "impact tracing without execution",
      "syntax checking as a safe preflight",
    ],
    endurance_status: "covered",
    exposure_decision: "covered_by_existing_dev_code_tools",
    endurance_probes: ["dev_code_symbols", "dev_code_dependencies", "dev_code_audit", "dev_code_impact", "dev_code_syntax_check", "dev_code_locate", "code_sample_js"],
    negative_controls: ["no user-code execution", "bounded output", "connector-safe file access"],
    hold_reason: "No hold; mechanism endurance is already covered.",
    required_next_step: "Keep parity guard current when GPT MCP code techniques change.",
  },
  {
    mechanism: "registry_governance_mechanisms",
    source_server: "GPT MCP registry subsystem",
    source_modules: ["core/registry_tools_safe.js"],
    source_tools: ["tool_registry_status", "tool_registry_list", "tool_registry_get_tool", "tool_registry_validate_tool", "tool_registry_policy", "tool_registry_preflight", "tool_registry_execute", "tool_registry_plan"],
    source_methods: [
      "read-only registry introspection",
      "policy metadata exposure",
      "known/enabled/allowed validation",
      "no hidden dispatch during metadata reads",
      "preflight before execution",
      "governance receipt discipline",
    ],
    endurance_status: "covered",
    exposure_decision: "covered_by_plugin_registry_and_governance_harness",
    endurance_probes: ["plugin_registry_status", "plugin_registry_list", "plugin_registry_get", "plugin_registry_audit", "_tests/smoke_stage8_2_execution_governance.js", "_tests/smoke_stage8_5_execution_receipt_verifier.js"],
    negative_controls: ["registry reads do not dispatch tools", "execution governance deny matrix", "receipt verifier"],
    hold_reason: "No Step39-critical need for name-identical tool_registry tools; governance techniques are represented by plugin registry and execution governance probes.",
    required_next_step: "Add tool-registry-named probes only if TEST MCP introduces a distinct runtime tool registry abstraction.",
  },
  {
    mechanism: "web_access_mechanisms",
    source_server: "GPT MCP web subsystem",
    source_modules: ["core/web_tools.js"],
    source_tools: ["http_get", "check_npm_package", "check_pypi_package", "fetch_github_file"],
    source_methods: [
      "allowlisted network access",
      "bounded fetch output",
      "package metadata lookup without code execution",
      "raw GitHub file fetch with no disk writes",
    ],
    endurance_status: "covered",
    exposure_decision: "covered_by_existing_net_tools",
    endurance_probes: ["net_http_get_allowlisted", "net_fetch_text_allowlisted", "net_check_url_head", "net_fetch_github_raw", "net_check_npm_package", "net_check_pypi_package"],
    negative_controls: ["network allowlist", "skip-network smoke mode", "bounded response body"],
    hold_reason: "No hold; mechanism endurance is already covered.",
    required_next_step: "Keep allowlist and schema probes current when network policy changes.",
  },
  {
    mechanism: "truth_drift_detection_mechanisms",
    source_server: "GPT MCP truth subsystem",
    source_modules: ["core/truth_tools.js"],
    source_tools: ["project_truth_audit", "code_runtime_map", "deploy_decision_guard", "change_workflow_simulator", "tool_usage_snapshot"],
    source_methods: [
      "declared-vs-runtime drift detection",
      "code-runtime map validation",
      "change workflow simulation",
      "source-of-truth boundary enforcement",
      "operator handoff/course consistency checks",
    ],
    endurance_status: "covered",
    exposure_decision: "internal_harness_is_sufficient_before_step39",
    endurance_probes: ["src/truth/project_truth_audit.js", "src/truth/code_runtime_map.js", "src/truth/change_workflow_simulator.js", "src/truth/parity_audit.js", "_tests/smoke_stage8_53a_truth_parity_internal.js", "_tests/smoke_workflow_state.js", "_tests/smoke_stage8_52_server_spec_current_truth.js"],
    negative_controls: ["workflow state/doc mismatch detection", "server spec current truth guard", "stage metadata restart note guard"],
    hold_reason: "Connector-visible truth tools can wait; internal drift-detection endurance is already represented and is sufficient before Step39.",
    required_next_step: "Expose truth tools only if a later stage explicitly needs connector-visible truth queries.",
  },
  {
    mechanism: "process_runner_policy_mechanisms",
    source_server: "GPT MCP process subsystem",
    source_modules: ["core/process_tools_safe.js"],
    source_tools: ["run_process", "process_runner_status"],
    source_methods: [
      "allowlisted process execution",
      "bounded cwd",
      "bounded timeout",
      "bounded stdout/stderr",
      "restricted environment inheritance",
      "shell-injection avoidance",
      "audit trail for process attempts",
      "denied-command behavior",
    ],
    endurance_status: "on_hold",
    exposure_decision: "defer_runtime_process_capability_before_step39",
    endurance_probes: ["_workflow/scripts/test_mcp_backup.ps1", "_workflow/scripts/test_mcp_deploy.ps1", "_workflow/scripts/test_mcp_rollback.ps1", "_tests/smoke_stage8_13_process_runner_observability.js"],
    negative_controls: ["process anomalies audited outside TEST MCP runtime", "no runtime process execution exposure"],
    hold_reason: "Runtime process execution is high-risk and not required for Step39. Existing workflow/control-plane smokes cover deployment process discipline; further process-runner probes can be deferred.",
    required_next_step: "Before any runtime process capability, add internal-only mock process-runner policy probes for allowlist, cwd, env, timeout, output bounds, and denial semantics.",
  },
  {
    mechanism: "remote_site_lifecycle_mechanisms",
    source_server: "GPT MCP remote-site subsystem",
    source_modules: ["core/remote_site_tools.js"],
    source_tools: ["list_remote_site_files", "read_remote_site_file", "write_remote_site_file", "edit_remote_site_file", "delete_remote_site_file", "move_remote_site_file", "restore_remote_site_file", "remote_site_runtime_status", "preview_remote_site_retention"],
    source_methods: [
      "bounded remote root",
      "path traversal denial",
      "read/write separation",
      "diff before replace",
      "backup outside public webroot",
      "soft delete/private trash",
      "restore metadata",
      "retention preview before cleanup",
      "per-call config reference",
    ],
    endurance_status: "on_hold",
    exposure_decision: "defer_remote_site_mock_harness_before_step39",
    endurance_probes: [],
    negative_controls: [],
    hold_reason: "Remote-site lifecycle is not on the Step39 critical path. A safe mock harness is useful later, but implementing it now would delay Step39 and risk scope creep.",
    required_next_step: "Before real remote-site work, add a mock remote-root harness with traversal, overwrite, private-trash, restore-metadata, diff, and retention-preview negative controls; do not use a real VPS for endurance probes.",
  },
  {
    mechanism: "deploy_rollback_control_plane_mechanisms",
    source_server: "GPT MCP root control-plane",
    source_modules: ["deploy.ps1", "rollback.ps1"],
    source_tools: ["Prepare", "Execute", "Rollback"],
    source_methods: [
      "backup before deploy",
      "operator-controlled execute/rollback",
      "topology-aware deploy scripts",
      "rollback point preservation",
      "control-plane auditability",
    ],
    endurance_status: "covered",
    exposure_decision: "workflow_control_plane_only",
    endurance_probes: ["_workflow/scripts/test_mcp_backup.ps1", "_workflow/scripts/test_mcp_deploy.ps1", "_workflow/scripts/test_mcp_rollback.ps1", "_tests/smoke_stage8_52d_control_plane_deploy_rollback.js"],
    negative_controls: ["no connector-visible deploy tools", "backup and rollback scripts remain workflow-only"],
    hold_reason: "No hold; workflow control-plane endurance is covered.",
    required_next_step: "Keep Stage 8 / Step 52d guard green and preserve operator-controlled deploy semantics.",
  },
];

const GPT_MCP_TOOLS_MECHANISMS = MECHANISM_ENDURANCE_MATRIX;

function buildMechanismParityReport() {
  const onHold = MECHANISM_ENDURANCE_MATRIX.filter((entry) => entry.endurance_status === "on_hold");
  const requiredNow = MECHANISM_ENDURANCE_MATRIX.filter((entry) => entry.endurance_status === "required_now");
  const covered = MECHANISM_ENDURANCE_MATRIX.filter((entry) => entry.endurance_status === "covered");

  return {
    version: MECHANISM_PARITY_MATRIX_VERSION,
    source: "GPT MCP mechanism technique/method/process groups",
    target: "TEST MCP endurance probes",
    total: MECHANISM_ENDURANCE_MATRIX.length,
    covered_count: covered.length,
    on_hold_count: onHold.length,
    required_now_count: requiredNow.length,
    status: requiredNow.length === 0 ? "step39_ready_with_on_hold_endurance_debt" : "required_endurance_gaps_present",
    mechanisms: MECHANISM_ENDURANCE_MATRIX,
  };
}

module.exports = {
  MECHANISM_PARITY_MATRIX_VERSION,
  MECHANISM_ENDURANCE_MATRIX,
  GPT_MCP_TOOLS_MECHANISMS,
  buildMechanismParityReport,
};
